namespace TFVpdSharp.Models;

// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class CMsgFieldID : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public global::System.Collections.Generic.List<CMsgField> field { get; set; } = new global::System.Collections.Generic.List<CMsgField>();

    [global::ProtoBuf.ProtoContract()]
    public partial class CMsgField : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint field_number
        {
            get { return __pbn__field_number.GetValueOrDefault(); }
            set { __pbn__field_number = value; }
        }
        public bool ShouldSerializefield_number() => __pbn__field_number != null;
        public void Resetfield_number() => __pbn__field_number = null;
        private uint? __pbn__field_number;

        [global::ProtoBuf.ProtoMember(2)]
        public uint repeated_index
        {
            get { return __pbn__repeated_index.GetValueOrDefault(); }
            set { __pbn__repeated_index = value; }
        }
        public bool ShouldSerializerepeated_index() => __pbn__repeated_index != null;
        public void Resetrepeated_index() => __pbn__repeated_index = null;
        private uint? __pbn__repeated_index;

    }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgUniversalFieldID : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue(EValueDefinitionSource.REFERENCE_DEFINES)]
    public EValueDefinitionSource source_type
    {
        get { return __pbn__source_type ?? EValueDefinitionSource.REFERENCE_DEFINES; }
        set { __pbn__source_type = value; }
    }
    public bool ShouldSerializesource_type() => __pbn__source_type != null;
    public void Resetsource_type() => __pbn__source_type = null;
    private EValueDefinitionSource? __pbn__source_type;

    [global::ProtoBuf.ProtoMember(2)]
    public CMsgProtoDefID defining_obj_id { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public CMsgFieldID field_id { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgVariableDefinition : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
        get { return __pbn__name ?? ""; }
        set { __pbn__name = value; }
    }
    public bool ShouldSerializename() => __pbn__name != null;
    public void Resetname() => __pbn__name = null;
    private string __pbn__name;

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue(true)]
    public bool inherit
    {
        get { return __pbn__inherit ?? true; }
        set { __pbn__inherit = value; }
    }
    public bool ShouldSerializeinherit() => __pbn__inherit != null;
    public void Resetinherit() => __pbn__inherit = null;
    private bool? __pbn__inherit;

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string value
    {
        get { return __pbn__value ?? ""; }
        set { __pbn__value = value; }
    }
    public bool ShouldSerializevalue() => __pbn__value != null;
    public void Resetvalue() => __pbn__value = null;
    private string __pbn__value;

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgProtoDefHeader : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public uint defindex { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
        get { return __pbn__name ?? ""; }
        set { __pbn__name = value; }
    }
    public bool ShouldSerializename() => __pbn__name != null;
    public void Resetname() => __pbn__name = null;
    private string __pbn__name;

    [global::ProtoBuf.ProtoMember(3)]
    public global::System.Collections.Generic.List<CMsgProtoDefID> prefabs { get; set; } = new global::System.Collections.Generic.List<CMsgProtoDefID>();

    [global::ProtoBuf.ProtoMember(4)]
    public global::System.Collections.Generic.List<string> tags { get; set; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(5)]
    [global::System.ComponentModel.DefaultValue(false)]
    public bool prefab_only
    {
        get { return __pbn__prefab_only ?? false; }
        set { __pbn__prefab_only = value; }
    }
    public bool ShouldSerializeprefab_only() => __pbn__prefab_only != null;
    public void Resetprefab_only() => __pbn__prefab_only = null;
    private bool? __pbn__prefab_only;

    [global::ProtoBuf.ProtoMember(6)]
    public global::System.Collections.Generic.List<CMsgVariableDefinition> variables { get; set; } = new global::System.Collections.Generic.List<CMsgVariableDefinition>();

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgValidTypes : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public global::System.Collections.Generic.List<ProtoDefTypes> types { get; set; } = new global::System.Collections.Generic.List<ProtoDefTypes>();

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgProtoDefID : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public uint defindex
    {
        get { return __pbn__defindex.GetValueOrDefault(); }
        set { __pbn__defindex = value; }
    }
    public bool ShouldSerializedefindex() => __pbn__defindex != null;
    public void Resetdefindex() => __pbn__defindex = null;
    private uint? __pbn__defindex;

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue(ProtoDefTypes.DEF_TYPE_QUEST_MAP_NODE)]
    public ProtoDefTypes type
    {
        get { return __pbn__type ?? ProtoDefTypes.DEF_TYPE_QUEST_MAP_NODE; }
        set { __pbn__type = value; }
    }
    public bool ShouldSerializetype() => __pbn__type != null;
    public void Resettype() => __pbn__type = null;
    private ProtoDefTypes? __pbn__type;

    [global::ProtoBuf.ProtoMember(3)]
    public CMsgQuestMapNodeDef instance_def_type_quest_map_node
    {
        get { return __pbn__instance.Is(3) ? ((CMsgQuestMapNodeDef)__pbn__instance.Object) : default(CMsgQuestMapNodeDef); }
        set { __pbn__instance = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
    }
    public bool ShouldSerializeinstance_def_type_quest_map_node() => __pbn__instance.Is(3);
    public void Resetinstance_def_type_quest_map_node() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__instance, 3);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__instance;

    [global::ProtoBuf.ProtoMember(5)]
    public CMsgQuestTheme instance_def_type_quest_theme
    {
        get { return __pbn__instance.Is(5) ? ((CMsgQuestTheme)__pbn__instance.Object) : default(CMsgQuestTheme); }
        set { __pbn__instance = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
    }
    public bool ShouldSerializeinstance_def_type_quest_theme() => __pbn__instance.Is(5);
    public void Resetinstance_def_type_quest_theme() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__instance, 5);

    [global::ProtoBuf.ProtoMember(6)]
    public CMsgQuestMapRegionDef instance_def_type_quest_map_region
    {
        get { return __pbn__instance.Is(6) ? ((CMsgQuestMapRegionDef)__pbn__instance.Object) : default(CMsgQuestMapRegionDef); }
        set { __pbn__instance = new global::ProtoBuf.DiscriminatedUnionObject(6, value); }
    }
    public bool ShouldSerializeinstance_def_type_quest_map_region() => __pbn__instance.Is(6);
    public void Resetinstance_def_type_quest_map_region() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__instance, 6);

    [global::ProtoBuf.ProtoMember(7)]
    public CMsgQuestDef instance_def_type_quest
    {
        get { return __pbn__instance.Is(7) ? ((CMsgQuestDef)__pbn__instance.Object) : default(CMsgQuestDef); }
        set { __pbn__instance = new global::ProtoBuf.DiscriminatedUnionObject(7, value); }
    }
    public bool ShouldSerializeinstance_def_type_quest() => __pbn__instance.Is(7);
    public void Resetinstance_def_type_quest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__instance, 7);

    [global::ProtoBuf.ProtoMember(8)]
    public CMsgQuestObjectiveDef instance_def_type_quest_objective
    {
        get { return __pbn__instance.Is(8) ? ((CMsgQuestObjectiveDef)__pbn__instance.Object) : default(CMsgQuestObjectiveDef); }
        set { __pbn__instance = new global::ProtoBuf.DiscriminatedUnionObject(8, value); }
    }
    public bool ShouldSerializeinstance_def_type_quest_objective() => __pbn__instance.Is(8);
    public void Resetinstance_def_type_quest_objective() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__instance, 8);

    [global::ProtoBuf.ProtoMember(9)]
    public CMsgPaintKit_Variables instance_def_type_paintkit_variables
    {
        get { return __pbn__instance.Is(9) ? ((CMsgPaintKit_Variables)__pbn__instance.Object) : default(CMsgPaintKit_Variables); }
        set { __pbn__instance = new global::ProtoBuf.DiscriminatedUnionObject(9, value); }
    }
    public bool ShouldSerializeinstance_def_type_paintkit_variables() => __pbn__instance.Is(9);
    public void Resetinstance_def_type_paintkit_variables() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__instance, 9);

    [global::ProtoBuf.ProtoMember(10)]
    public CMsgPaintKit_Operation instance_def_type_paintkit_operation
    {
        get { return __pbn__instance.Is(10) ? ((CMsgPaintKit_Operation)__pbn__instance.Object) : default(CMsgPaintKit_Operation); }
        set { __pbn__instance = new global::ProtoBuf.DiscriminatedUnionObject(10, value); }
    }
    public bool ShouldSerializeinstance_def_type_paintkit_operation() => __pbn__instance.Is(10);
    public void Resetinstance_def_type_paintkit_operation() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__instance, 10);

    [global::ProtoBuf.ProtoMember(11)]
    public CMsgPaintKit_ItemDefinition instance_def_type_paintkit_item_definition
    {
        get { return __pbn__instance.Is(11) ? ((CMsgPaintKit_ItemDefinition)__pbn__instance.Object) : default(CMsgPaintKit_ItemDefinition); }
        set { __pbn__instance = new global::ProtoBuf.DiscriminatedUnionObject(11, value); }
    }
    public bool ShouldSerializeinstance_def_type_paintkit_item_definition() => __pbn__instance.Is(11);
    public void Resetinstance_def_type_paintkit_item_definition() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__instance, 11);

    [global::ProtoBuf.ProtoMember(12)]
    public CMsgPaintKit_Definition instance_def_type_paintkit_definition
    {
        get { return __pbn__instance.Is(12) ? ((CMsgPaintKit_Definition)__pbn__instance.Object) : default(CMsgPaintKit_Definition); }
        set { __pbn__instance = new global::ProtoBuf.DiscriminatedUnionObject(12, value); }
    }
    public bool ShouldSerializeinstance_def_type_paintkit_definition() => __pbn__instance.Is(12);
    public void Resetinstance_def_type_paintkit_definition() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__instance, 12);

    [global::ProtoBuf.ProtoMember(13)]
    public CMsgHeaderOnly instance_def_type_header_only
    {
        get { return __pbn__instance.Is(13) ? ((CMsgHeaderOnly)__pbn__instance.Object) : default(CMsgHeaderOnly); }
        set { __pbn__instance = new global::ProtoBuf.DiscriminatedUnionObject(13, value); }
    }
    public bool ShouldSerializeinstance_def_type_header_only() => __pbn__instance.Is(13);
    public void Resetinstance_def_type_header_only() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__instance, 13);

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgQuestObjectiveDef : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public CMsgProtoDefHeader header { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string loc_desctoken
    {
        get { return __pbn__loc_desctoken ?? ""; }
        set { __pbn__loc_desctoken = value; }
    }
    public bool ShouldSerializeloc_desctoken() => __pbn__loc_desctoken != null;
    public void Resetloc_desctoken() => __pbn__loc_desctoken = null;
    private string __pbn__loc_desctoken;

    [global::ProtoBuf.ProtoMember(3)]
    public uint points
    {
        get { return __pbn__points.GetValueOrDefault(); }
        set { __pbn__points = value; }
    }
    public bool ShouldSerializepoints() => __pbn__points != null;
    public void Resetpoints() => __pbn__points = null;
    private uint? __pbn__points;

    [global::ProtoBuf.ProtoMember(5)]
    public uint conditions_defindex
    {
        get { return __pbn__conditions_defindex.GetValueOrDefault(); }
        set { __pbn__conditions_defindex = value; }
    }
    public bool ShouldSerializeconditions_defindex() => __pbn__conditions_defindex != null;
    public void Resetconditions_defindex() => __pbn__conditions_defindex = null;
    private uint? __pbn__conditions_defindex;

    [global::ProtoBuf.ProtoMember(8)]
    public global::System.Collections.Generic.List<string> map { get; set; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(9)]
    public global::System.Collections.Generic.List<ETF2GameModes> game_mode { get; set; } = new global::System.Collections.Generic.List<ETF2GameModes>();

    [global::ProtoBuf.ProtoMember(10)]
    [global::System.ComponentModel.DefaultValue(ETF2Team.TF_TEAM_RED)]
    public ETF2Team team
    {
        get { return __pbn__team ?? ETF2Team.TF_TEAM_RED; }
        set { __pbn__team = value; }
    }
    public bool ShouldSerializeteam() => __pbn__team != null;
    public void Resetteam() => __pbn__team = null;
    private ETF2Team? __pbn__team;

    [global::ProtoBuf.ProtoMember(11)]
    public global::System.Collections.Generic.List<CMsgVarField> condition_vars { get; set; } = new global::System.Collections.Generic.List<CMsgVarField>();

    [global::ProtoBuf.ProtoMember(12)]
    public global::System.Collections.Generic.List<CMsgVarField> classes_vars { get; set; } = new global::System.Collections.Generic.List<CMsgVarField>();

    [global::ProtoBuf.ProtoMember(13)]
    public global::System.Collections.Generic.List<ETF2Conditions> conditions { get; set; } = new global::System.Collections.Generic.List<ETF2Conditions>();

    [global::ProtoBuf.ProtoMember(14)]
    [global::System.ComponentModel.DefaultValue(LogicalOperation.AND)]
    public LogicalOperation condition_logic
    {
        get { return __pbn__condition_logic ?? LogicalOperation.AND; }
        set { __pbn__condition_logic = value; }
    }
    public bool ShouldSerializecondition_logic() => __pbn__condition_logic != null;
    public void Resetcondition_logic() => __pbn__condition_logic = null;
    private LogicalOperation? __pbn__condition_logic;

    [global::ProtoBuf.ProtoMember(15)]
    public global::System.Collections.Generic.List<string> item_name { get; set; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(16)]
    [global::System.ComponentModel.DefaultValue(LogicalOperation.AND)]
    public LogicalOperation item_logic
    {
        get { return __pbn__item_logic ?? LogicalOperation.AND; }
        set { __pbn__item_logic = value; }
    }
    public bool ShouldSerializeitem_logic() => __pbn__item_logic != null;
    public void Resetitem_logic() => __pbn__item_logic = null;
    private LogicalOperation? __pbn__item_logic;

    [global::ProtoBuf.ProtoMember(17)]
    public uint jump_state
    {
        get { return __pbn__jump_state.GetValueOrDefault(); }
        set { __pbn__jump_state = value; }
    }
    public bool ShouldSerializejump_state() => __pbn__jump_state != null;
    public void Resetjump_state() => __pbn__jump_state = null;
    private uint? __pbn__jump_state;

    [global::ProtoBuf.ProtoContract()]
    public enum ETF2GameModes
    {
        kGameCategory_Escort = 0,
        kGameCategory_CTF = 1,
        kGameCategory_AttackDefense = 2,
        kGameCategory_Koth = 3,
        kGameCategory_CP = 4,
        kGameCategory_EscortRace = 5,
        kGameCategory_EventMix = 6,
        kGameCategory_SD = 7,
        kGameCategory_Quickplay = 8,
        kGameCategory_Event247 = 9,
        kGameCategory_Arena = 10,
        kGameCategory_RobotDestruction = 11,
        kGameCategory_Powerup = 12,
        kGameCategory_Featured = 13,
        kGameCategory_Passtime = 14,
        kGameCategory_Community_Update = 15,
        kGameCategory_Misc = 16,
        kGameCategory_Competitive_6v6 = 17,
        kGameCategory_Other = 18,
        kGameCategory_Halloween = 19,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ETF2Conditions
    {
        TF_COND_AIMING = 0,
        TF_COND_ZOOMED = 1,
        TF_COND_DISGUISING = 2,
        TF_COND_DISGUISED = 3,
        TF_COND_STEALTHED = 4,
        TF_COND_INVULNERABLE = 5,
        TF_COND_TELEPORTED = 6,
        TF_COND_TAUNTING = 7,
        TF_COND_INVULNERABLE_WEARINGOFF = 8,
        TF_COND_STEALTHED_BLINK = 9,
        TF_COND_SELECTED_TO_TELEPORT = 10,
        TF_COND_CRITBOOSTED = 11,
        TF_COND_TMPDAMAGEBONUS = 12,
        TF_COND_FEIGN_DEATH = 13,
        TF_COND_PHASE = 14,
        TF_COND_STUNNED = 15,
        TF_COND_OFFENSEBUFF = 16,
        TF_COND_SHIELD_CHARGE = 17,
        TF_COND_DEMO_BUFF = 18,
        TF_COND_ENERGY_BUFF = 19,
        TF_COND_RADIUSHEAL = 20,
        TF_COND_HEALTH_BUFF = 21,
        TF_COND_BURNING = 22,
        TF_COND_HEALTH_OVERHEALED = 23,
        TF_COND_URINE = 24,
        TF_COND_BLEEDING = 25,
        TF_COND_DEFENSEBUFF = 26,
        TF_COND_MAD_MILK = 27,
        TF_COND_MEGAHEAL = 28,
        TF_COND_REGENONDAMAGEBUFF = 29,
        TF_COND_MARKEDFORDEATH = 30,
        TF_COND_NOHEALINGDAMAGEBUFF = 31,
        TF_COND_SPEED_BOOST = 32,
        TF_COND_CRITBOOSTED_PUMPKIN = 33,
        TF_COND_CRITBOOSTED_USER_BUFF = 34,
        TF_COND_CRITBOOSTED_DEMO_CHARGE = 35,
        TF_COND_SODAPOPPER_HYPE = 36,
        TF_COND_CRITBOOSTED_FIRST_BLOOD = 37,
        TF_COND_CRITBOOSTED_BONUS_TIME = 38,
        TF_COND_CRITBOOSTED_CTF_CAPTURE = 39,
        TF_COND_CRITBOOSTED_ON_KILL = 40,
        TF_COND_CANNOT_SWITCH_FROM_MELEE = 41,
        TF_COND_DEFENSEBUFF_NO_CRIT_BLOCK = 42,
        TF_COND_REPROGRAMMED = 43,
        TF_COND_CRITBOOSTED_RAGE_BUFF = 44,
        TF_COND_DEFENSEBUFF_HIGH = 45,
        TF_COND_SNIPERCHARGE_RAGE_BUFF = 46,
        TF_COND_DISGUISE_WEARINGOFF = 47,
        TF_COND_MARKEDFORDEATH_SILENT = 48,
        TF_COND_DISGUISED_AS_DISPENSER = 49,
        TF_COND_SAPPED = 50,
        TF_COND_INVULNERABLE_HIDE_UNLESS_DAMAGED = 51,
        TF_COND_INVULNERABLE_USER_BUFF = 52,
        TF_COND_HALLOWEEN_BOMB_HEAD = 53,
        TF_COND_HALLOWEEN_THRILLER = 54,
        TF_COND_RADIUSHEAL_ON_DAMAGE = 55,
        TF_COND_CRITBOOSTED_CARD_EFFECT = 56,
        TF_COND_INVULNERABLE_CARD_EFFECT = 57,
        TF_COND_MEDIGUN_UBER_BULLET_RESIST = 58,
        TF_COND_MEDIGUN_UBER_BLAST_RESIST = 59,
        TF_COND_MEDIGUN_UBER_FIRE_RESIST = 60,
        TF_COND_MEDIGUN_SMALL_BULLET_RESIST = 61,
        TF_COND_MEDIGUN_SMALL_BLAST_RESIST = 62,
        TF_COND_MEDIGUN_SMALL_FIRE_RESIST = 63,
        TF_COND_STEALTHED_USER_BUFF = 64,
        TF_COND_MEDIGUN_DEBUFF = 65,
        TF_COND_STEALTHED_USER_BUFF_FADING = 66,
        TF_COND_BULLET_IMMUNE = 67,
        TF_COND_BLAST_IMMUNE = 68,
        TF_COND_FIRE_IMMUNE = 69,
        TF_COND_PREVENT_DEATH = 70,
        TF_COND_MVM_BOT_STUN_RADIOWAVE = 71,
        TF_COND_HALLOWEEN_SPEED_BOOST = 72,
        TF_COND_HALLOWEEN_QUICK_HEAL = 73,
        TF_COND_HALLOWEEN_GIANT = 74,
        TF_COND_HALLOWEEN_TINY = 75,
        TF_COND_HALLOWEEN_IN_HELL = 76,
        TF_COND_HALLOWEEN_GHOST_MODE = 77,
        TF_COND_MINICRITBOOSTED_ON_KILL = 78,
        TF_COND_OBSCURED_SMOKE = 79,
        TF_COND_PARACHUTE_ACTIVE = 80,
        TF_COND_BLASTJUMPING = 81,
        TF_COND_HALLOWEEN_KART = 82,
        TF_COND_HALLOWEEN_KART_DASH = 83,
        TF_COND_BALLOON_HEAD = 84,
        TF_COND_MELEE_ONLY = 85,
        TF_COND_SWIMMING_CURSE = 86,
        TF_COND_FREEZE_INPUT = 87,
        TF_COND_HALLOWEEN_KART_CAGE = 88,
        TF_COND_DONOTUSE_0 = 89,
        TF_COND_RUNE_STRENGTH = 90,
        TF_COND_RUNE_HASTE = 91,
        TF_COND_RUNE_REGEN = 92,
        TF_COND_RUNE_RESIST = 93,
        TF_COND_RUNE_VAMPIRE = 94,
        TF_COND_RUNE_REFLECT = 95,
        TF_COND_RUNE_PRECISION = 96,
        TF_COND_RUNE_AGILITY = 97,
        TF_COND_GRAPPLINGHOOK = 98,
        TF_COND_GRAPPLINGHOOK_SAFEFALL = 99,
        TF_COND_GRAPPLINGHOOK_LATCHED = 100,
        TF_COND_GRAPPLINGHOOK_BLEEDING = 101,
        TF_COND_AFTERBURN_IMMUNE = 102,
        TF_COND_RUNE_KNOCKOUT = 103,
        TF_COND_RUNE_IMBALANCE = 104,
        TF_COND_CRITBOOSTED_RUNE_TEMP = 105,
        TF_COND_PASSTIME_INTERCEPTION = 106,
        TF_COND_SWIMMING_NO_EFFECTS = 107,
        TF_COND_PURGATORY = 108,
        TF_COND_RUNE_KING = 109,
        TF_COND_RUNE_PLAGUE = 110,
        TF_COND_RUNE_SUPERNOVA = 111,
        TF_COND_PLAGUE = 112,
        TF_COND_KING_BUFFED = 113,
        TF_COND_TEAM_GLOWS = 114,
        TF_COND_KNOCKED_INTO_AIR = 115,
        TF_COND_COMPETITIVE_WINNER = 116,
        TF_COND_COMPETITIVE_LOSER = 117,
        TF_COND_HEALING_DEBUFF = 118,
        TF_COND_PASSTIME_PENALTY_DEBUFF = 119,
        TF_COND_PARACHUTE_DEPLOYED = 120,
        TF_COND_NO_COMBAT_SPEED_BOOST = 121,
        TF_COND_TRANQ_SPY_BOOST = 122,
        TF_COND_TRANQ_MARKED = 123,
        TF_COND_ROCKETPACK = 126,
        TF_COND_ROCKETPACK_PASSENGER = 127,
        TF_COND_STEALTHED_PHASE = 128,
        TF_COND_CLIP_OVERLOAD = 129,
        TF_COND_SPY_CLASS_STEAL = 130,
        TF_COND_GAS = 131,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ETF2Team
    {
        TF_TEAM_RED = 2,
        TF_TEAM_BLUE = 3,
    }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgQuestDef : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public CMsgProtoDefHeader header { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public uint max_points_0
    {
        get { return __pbn__max_points_0.GetValueOrDefault(); }
        set { __pbn__max_points_0 = value; }
    }
    public bool ShouldSerializemax_points_0() => __pbn__max_points_0 != null;
    public void Resetmax_points_0() => __pbn__max_points_0 = null;
    private uint? __pbn__max_points_0;

    [global::ProtoBuf.ProtoMember(3)]
    public uint max_points_1
    {
        get { return __pbn__max_points_1.GetValueOrDefault(); }
        set { __pbn__max_points_1 = value; }
    }
    public bool ShouldSerializemax_points_1() => __pbn__max_points_1 != null;
    public void Resetmax_points_1() => __pbn__max_points_1 = null;
    private uint? __pbn__max_points_1;

    [global::ProtoBuf.ProtoMember(4)]
    public uint max_points_2
    {
        get { return __pbn__max_points_2.GetValueOrDefault(); }
        set { __pbn__max_points_2 = value; }
    }
    public bool ShouldSerializemax_points_2() => __pbn__max_points_2 != null;
    public void Resetmax_points_2() => __pbn__max_points_2 = null;
    private uint? __pbn__max_points_2;

    [global::ProtoBuf.ProtoMember(5)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name_loctoken
    {
        get { return __pbn__name_loctoken ?? ""; }
        set { __pbn__name_loctoken = value; }
    }
    public bool ShouldSerializename_loctoken() => __pbn__name_loctoken != null;
    public void Resetname_loctoken() => __pbn__name_loctoken = null;
    private string __pbn__name_loctoken;

    [global::ProtoBuf.ProtoMember(7)]
    [global::System.ComponentModel.DefaultValue("")]
    public string operation
    {
        get { return __pbn__operation ?? ""; }
        set { __pbn__operation = value; }
    }
    public bool ShouldSerializeoperation() => __pbn__operation != null;
    public void Resetoperation() => __pbn__operation = null;
    private string __pbn__operation;

    [global::ProtoBuf.ProtoMember(8)]
    public MMCriteria mm_criteria { get; set; }

    [global::ProtoBuf.ProtoMember(12)]
    [global::System.ComponentModel.DefaultValue("")]
    public string node_image
    {
        get { return __pbn__node_image ?? ""; }
        set { __pbn__node_image = value; }
    }
    public bool ShouldSerializenode_image() => __pbn__node_image != null;
    public void Resetnode_image() => __pbn__node_image = null;
    private string __pbn__node_image;

    [global::ProtoBuf.ProtoMember(13)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon_image
    {
        get { return __pbn__icon_image ?? ""; }
        set { __pbn__icon_image = value; }
    }
    public bool ShouldSerializeicon_image() => __pbn__icon_image != null;
    public void Reseticon_image() => __pbn__icon_image = null;
    private string __pbn__icon_image;

    [global::ProtoBuf.ProtoMember(14)]
    public CMsgProtoDefID theme { get; set; }

    [global::ProtoBuf.ProtoMember(15)]
    public global::System.Collections.Generic.List<string> loaner_names { get; set; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(16)]
    public global::System.Collections.Generic.List<ObjectiveInstance> objectives { get; set; } = new global::System.Collections.Generic.List<ObjectiveInstance>();

    [global::ProtoBuf.ProtoMember(17)]
    public global::System.Collections.Generic.List<string> map { get; set; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoContract()]
    public partial class MMCriteria : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string group_name
        {
            get { return __pbn__group_name ?? ""; }
            set { __pbn__group_name = value; }
        }
        public bool ShouldSerializegroup_name() => __pbn__group_name != null;
        public void Resetgroup_name() => __pbn__group_name = null;
        private string __pbn__group_name;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string category_name
        {
            get { return __pbn__category_name ?? ""; }
            set { __pbn__category_name = value; }
        }
        public bool ShouldSerializecategory_name() => __pbn__category_name != null;
        public void Resetcategory_name() => __pbn__category_name = null;
        private string __pbn__category_name;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string map_name
        {
            get { return __pbn__map_name ?? ""; }
            set { __pbn__map_name = value; }
        }
        public bool ShouldSerializemap_name() => __pbn__map_name != null;
        public void Resetmap_name() => __pbn__map_name = null;
        private string __pbn__map_name;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ObjectiveInstance : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public CMsgProtoDefID objective { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(EQuestPoints.QUEST_POINTS_NOVICE)]
        public EQuestPoints point_type
        {
            get { return __pbn__point_type ?? EQuestPoints.QUEST_POINTS_NOVICE; }
            set { __pbn__point_type = value; }
        }
        public bool ShouldSerializepoint_type() => __pbn__point_type != null;
        public void Resetpoint_type() => __pbn__point_type = null;
        private EQuestPoints? __pbn__point_type;

        [global::ProtoBuf.ProtoMember(3)]
        public uint point_value
        {
            get { return __pbn__point_value.GetValueOrDefault(); }
            set { __pbn__point_value = value; }
        }
        public bool ShouldSerializepoint_value() => __pbn__point_value != null;
        public void Resetpoint_value() => __pbn__point_value = null;
        private uint? __pbn__point_value;

    }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgQuestMapStoreItem : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public CMsgProtoDefHeader header { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string item_name
    {
        get { return __pbn__item_name ?? ""; }
        set { __pbn__item_name = value; }
    }
    public bool ShouldSerializeitem_name() => __pbn__item_name != null;
    public void Resetitem_name() => __pbn__item_name = null;
    private string __pbn__item_name;

    [global::ProtoBuf.ProtoMember(6)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reward_lootlist_name
    {
        get { return __pbn__reward_lootlist_name ?? ""; }
        set { __pbn__reward_lootlist_name = value; }
    }
    public bool ShouldSerializereward_lootlist_name() => __pbn__reward_lootlist_name != null;
    public void Resetreward_lootlist_name() => __pbn__reward_lootlist_name = null;
    private string __pbn__reward_lootlist_name;

    [global::ProtoBuf.ProtoMember(3)]
    public CMsgVarField price { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public uint purchase_limit
    {
        get { return __pbn__purchase_limit.GetValueOrDefault(); }
        set { __pbn__purchase_limit = value; }
    }
    public bool ShouldSerializepurchase_limit() => __pbn__purchase_limit != null;
    public void Resetpurchase_limit() => __pbn__purchase_limit = null;
    private uint? __pbn__purchase_limit;

    [global::ProtoBuf.ProtoMember(5)]
    public uint sort_group
    {
        get { return __pbn__sort_group.GetValueOrDefault(); }
        set { __pbn__sort_group = value; }
    }
    public bool ShouldSerializesort_group() => __pbn__sort_group != null;
    public void Resetsort_group() => __pbn__sort_group = null;
    private uint? __pbn__sort_group;

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgQuestMapRegionDef : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public CMsgProtoDefHeader header { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
        get { return __pbn__name ?? ""; }
        set { __pbn__name = value; }
    }
    public bool ShouldSerializename() => __pbn__name != null;
    public void Resetname() => __pbn__name = null;
    private string __pbn__name;

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resfile
    {
        get { return __pbn__resfile ?? ""; }
        set { __pbn__resfile = value; }
    }
    public bool ShouldSerializeresfile() => __pbn__resfile != null;
    public void Resetresfile() => __pbn__resfile = null;
    private string __pbn__resfile;

    [global::ProtoBuf.ProtoMember(4)]
    public global::System.Collections.Generic.List<RegionLink> links { get; set; } = new global::System.Collections.Generic.List<RegionLink>();

    [global::ProtoBuf.ProtoMember(5)]
    public CMsgProtoDefID return_link { get; set; }

    [global::ProtoBuf.ProtoMember(6)]
    public float radio_freq
    {
        get { return __pbn__radio_freq.GetValueOrDefault(); }
        set { __pbn__radio_freq = value; }
    }
    public bool ShouldSerializeradio_freq() => __pbn__radio_freq != null;
    public void Resetradio_freq() => __pbn__radio_freq = null;
    private float? __pbn__radio_freq;

    [global::ProtoBuf.ProtoMember(7)]
    public float zoom_scale
    {
        get { return __pbn__zoom_scale.GetValueOrDefault(); }
        set { __pbn__zoom_scale = value; }
    }
    public bool ShouldSerializezoom_scale() => __pbn__zoom_scale != null;
    public void Resetzoom_scale() => __pbn__zoom_scale = null;
    private float? __pbn__zoom_scale;

    [global::ProtoBuf.ProtoMember(8)]
    public CMsgProtoDefID star_type { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegionLink : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public CMsgProtoDefID target_region_defid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint xpos
        {
            get { return __pbn__xpos.GetValueOrDefault(); }
            set { __pbn__xpos = value; }
        }
        public bool ShouldSerializexpos() => __pbn__xpos != null;
        public void Resetxpos() => __pbn__xpos = null;
        private uint? __pbn__xpos;

        [global::ProtoBuf.ProtoMember(3)]
        public uint ypos
        {
            get { return __pbn__ypos.GetValueOrDefault(); }
            set { __pbn__ypos = value; }
        }
        public bool ShouldSerializeypos() => __pbn__ypos != null;
        public void Resetypos() => __pbn__ypos = null;
        private uint? __pbn__ypos;

    }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgVarField : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string variable
    {
        get { return __pbn__variable ?? ""; }
        set { __pbn__variable = value; }
    }
    public bool ShouldSerializevariable() => __pbn__variable != null;
    public void Resetvariable() => __pbn__variable = null;
    private string __pbn__variable;

    [global::ProtoBuf.ProtoMember(2)]
    public float @float
    {
        get { return __pbn__value.Is(2) ? __pbn__value.Single : default(float); }
        set { __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(2, value); }
    }
    public bool ShouldSerializefloat() => __pbn__value.Is(2);
    public void Resetfloat() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 2);

    private global::ProtoBuf.DiscriminatedUnion64Object __pbn__value;

    [global::ProtoBuf.ProtoMember(3)]
    public double @double
    {
        get { return __pbn__value.Is(3) ? __pbn__value.Double : default(double); }
        set { __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(3, value); }
    }
    public bool ShouldSerializedouble() => __pbn__value.Is(3);
    public void Resetdouble() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 3);

    [global::ProtoBuf.ProtoMember(4)]
    public uint uint32
    {
        get { return __pbn__value.Is(4) ? __pbn__value.UInt32 : default(uint); }
        set { __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(4, value); }
    }
    public bool ShouldSerializeuint32() => __pbn__value.Is(4);
    public void Resetuint32() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 4);

    [global::ProtoBuf.ProtoMember(5)]
    public ulong uint64
    {
        get { return __pbn__value.Is(5) ? __pbn__value.UInt64 : default(ulong); }
        set { __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(5, value); }
    }
    public bool ShouldSerializeuint64() => __pbn__value.Is(5);
    public void Resetuint64() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 5);

    [global::ProtoBuf.ProtoMember(6, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int sint32
    {
        get { return __pbn__value.Is(6) ? __pbn__value.Int32 : default(int); }
        set { __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(6, value); }
    }
    public bool ShouldSerializesint32() => __pbn__value.Is(6);
    public void Resetsint32() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 6);

    [global::ProtoBuf.ProtoMember(7, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public long sint64
    {
        get { return __pbn__value.Is(7) ? __pbn__value.Int64 : default(long); }
        set { __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(7, value); }
    }
    public bool ShouldSerializesint64() => __pbn__value.Is(7);
    public void Resetsint64() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 7);

    [global::ProtoBuf.ProtoMember(8)]
    public bool @bool
    {
        get { return __pbn__value.Is(8) ? __pbn__value.Boolean : default(bool); }
        set { __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(8, value); }
    }
    public bool ShouldSerializebool() => __pbn__value.Is(8);
    public void Resetbool() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 8);

    [global::ProtoBuf.ProtoMember(9)]
    [global::System.ComponentModel.DefaultValue("")]
    public string @string
    {
        get { return __pbn__value.Is(9) ? ((string)__pbn__value.Object) : ""; }
        set { __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(9, value); }
    }
    public bool ShouldSerializestring() => __pbn__value.Is(9);
    public void Resetstring() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 9);

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgQuestMapStarType : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public CMsgProtoDefHeader header { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
        get { return __pbn__name ?? ""; }
        set { __pbn__name = value; }
    }
    public bool ShouldSerializename() => __pbn__name != null;
    public void Resetname() => __pbn__name = null;
    private string __pbn__name;

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgQuestMapNodeDef : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public CMsgProtoDefHeader header { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name_loctoken
    {
        get { return __pbn__name_loctoken ?? ""; }
        set { __pbn__name_loctoken = value; }
    }
    public bool ShouldSerializename_loctoken() => __pbn__name_loctoken != null;
    public void Resetname_loctoken() => __pbn__name_loctoken = null;
    private string __pbn__name_loctoken;

    [global::ProtoBuf.ProtoMember(6)]
    public float x_pos
    {
        get { return __pbn__x_pos.GetValueOrDefault(); }
        set { __pbn__x_pos = value; }
    }
    public bool ShouldSerializex_pos() => __pbn__x_pos != null;
    public void Resetx_pos() => __pbn__x_pos = null;
    private float? __pbn__x_pos;

    [global::ProtoBuf.ProtoMember(7)]
    public float y_pos
    {
        get { return __pbn__y_pos.GetValueOrDefault(); }
        set { __pbn__y_pos = value; }
    }
    public bool ShouldSerializey_pos() => __pbn__y_pos != null;
    public void Resety_pos() => __pbn__y_pos = null;
    private float? __pbn__y_pos;

    [global::ProtoBuf.ProtoMember(9)]
    public CMsgQuestMapNodeCondition condition { get; set; }

    [global::ProtoBuf.ProtoMember(10)]
    public CMsgProtoDefID owning_region { get; set; }

    [global::ProtoBuf.ProtoMember(11)]
    public global::System.Collections.Generic.List<CMsgProtoDefID> quest_options { get; set; } = new global::System.Collections.Generic.List<CMsgProtoDefID>();

    [global::ProtoBuf.ProtoMember(16)]
    [global::System.ComponentModel.DefaultValue("")]
    public string associated_operation
    {
        get { return __pbn__associated_operation ?? ""; }
        set { __pbn__associated_operation = value; }
    }
    public bool ShouldSerializeassociated_operation() => __pbn__associated_operation != null;
    public void Resetassociated_operation() => __pbn__associated_operation = null;
    private string __pbn__associated_operation;

    [global::ProtoBuf.ProtoMember(18)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reward_item_name
    {
        get { return __pbn__reward_item_name ?? ""; }
        set { __pbn__reward_item_name = value; }
    }
    public bool ShouldSerializereward_item_name() => __pbn__reward_item_name != null;
    public void Resetreward_item_name() => __pbn__reward_item_name = null;
    private string __pbn__reward_item_name;

    [global::ProtoBuf.ProtoMember(22)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reward_lootlist_name
    {
        get { return __pbn__reward_lootlist_name ?? ""; }
        set { __pbn__reward_lootlist_name = value; }
    }
    public bool ShouldSerializereward_lootlist_name() => __pbn__reward_lootlist_name != null;
    public void Resetreward_lootlist_name() => __pbn__reward_lootlist_name = null;
    private string __pbn__reward_lootlist_name;

    [global::ProtoBuf.ProtoMember(19)]
    [global::System.ComponentModel.DefaultValue(ENodeCashReward.CASH_REWARD_NONE)]
    public ENodeCashReward cash_reward
    {
        get { return __pbn__cash_reward ?? ENodeCashReward.CASH_REWARD_NONE; }
        set { __pbn__cash_reward = value; }
    }
    public bool ShouldSerializecash_reward() => __pbn__cash_reward != null;
    public void Resetcash_reward() => __pbn__cash_reward = null;
    private ENodeCashReward? __pbn__cash_reward;

    [global::ProtoBuf.ProtoMember(20)]
    public CMsgProtoDefID star_type { get; set; }

    [global::ProtoBuf.ProtoMember(21)]
    [global::System.ComponentModel.DefaultValue(1)]
    public uint stars_to_unlock
    {
        get { return __pbn__stars_to_unlock ?? 1; }
        set { __pbn__stars_to_unlock = value; }
    }
    public bool ShouldSerializestars_to_unlock() => __pbn__stars_to_unlock != null;
    public void Resetstars_to_unlock() => __pbn__stars_to_unlock = null;
    private uint? __pbn__stars_to_unlock;

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgPaintKit_Variables : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public CMsgProtoDefHeader header { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgPaintKit_Operation_TextureStage : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public CMsgVarField texture { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public CMsgVarField texture_red { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public CMsgVarField texture_blue { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public CMsgVarField adjust_black { get; set; }

    [global::ProtoBuf.ProtoMember(5)]
    public CMsgVarField adjust_offset { get; set; }

    [global::ProtoBuf.ProtoMember(6)]
    public CMsgVarField adjust_gamma { get; set; }

    [global::ProtoBuf.ProtoMember(7)]
    public CMsgVarField rotation { get; set; }

    [global::ProtoBuf.ProtoMember(8)]
    public CMsgVarField translate_u { get; set; }

    [global::ProtoBuf.ProtoMember(9)]
    public CMsgVarField translate_v { get; set; }

    [global::ProtoBuf.ProtoMember(10)]
    public CMsgVarField scale_uv { get; set; }

    [global::ProtoBuf.ProtoMember(11)]
    public CMsgVarField flip_u { get; set; }

    [global::ProtoBuf.ProtoMember(12)]
    public CMsgVarField flip_v { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgPaintKit_Operation_CombineStage : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public CMsgVarField adjust_black { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public CMsgVarField adjust_offset { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public CMsgVarField adjust_gamma { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public CMsgVarField rotation { get; set; }

    [global::ProtoBuf.ProtoMember(5)]
    public CMsgVarField translate_u { get; set; }

    [global::ProtoBuf.ProtoMember(6)]
    public CMsgVarField translate_v { get; set; }

    [global::ProtoBuf.ProtoMember(7)]
    public CMsgVarField scale_uv { get; set; }

    [global::ProtoBuf.ProtoMember(8)]
    public CMsgVarField flip_u { get; set; }

    [global::ProtoBuf.ProtoMember(9)]
    public CMsgVarField flip_v { get; set; }

    [global::ProtoBuf.ProtoMember(11)]
    public global::System.Collections.Generic.List<CMsgPaintKit_OperationNode> operation_node { get; set; } = new global::System.Collections.Generic.List<CMsgPaintKit_OperationNode>();

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgPaintKit_Operation_SelectStage : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public CMsgVarField groups { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public global::System.Collections.Generic.List<CMsgVarField> select { get; set; } = new global::System.Collections.Generic.List<CMsgVarField>();

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgPaintKit_Operation_Sticker : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public CMsgVarField @base { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public CMsgVarField weight { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public CMsgVarField spec { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgPaintKit_Operation_StickerStage : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public global::System.Collections.Generic.List<CMsgPaintKit_Operation_Sticker> sticker { get; set; } = new global::System.Collections.Generic.List<CMsgPaintKit_Operation_Sticker>();

    [global::ProtoBuf.ProtoMember(2)]
    public CMsgVarField dest_tl { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public CMsgVarField dest_tr { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public CMsgVarField dest_bl { get; set; }

    [global::ProtoBuf.ProtoMember(5)]
    public CMsgVarField adjust_black { get; set; }

    [global::ProtoBuf.ProtoMember(6)]
    public CMsgVarField adjust_offset { get; set; }

    [global::ProtoBuf.ProtoMember(7)]
    public CMsgVarField adjust_gamma { get; set; }

    [global::ProtoBuf.ProtoMember(9)]
    public global::System.Collections.Generic.List<CMsgPaintKit_OperationNode> operation_node { get; set; } = new global::System.Collections.Generic.List<CMsgPaintKit_OperationNode>();

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgPaintKit_OperationStage : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public CMsgPaintKit_Operation_TextureStage texture_lookup
    {
        get { return __pbn__stage.Is(1) ? ((CMsgPaintKit_Operation_TextureStage)__pbn__stage.Object) : default(CMsgPaintKit_Operation_TextureStage); }
        set { __pbn__stage = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
    }
    public bool ShouldSerializetexture_lookup() => __pbn__stage.Is(1);
    public void Resettexture_lookup() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__stage, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__stage;

    [global::ProtoBuf.ProtoMember(2)]
    public CMsgPaintKit_Operation_CombineStage combine_add
    {
        get { return __pbn__stage.Is(2) ? ((CMsgPaintKit_Operation_CombineStage)__pbn__stage.Object) : default(CMsgPaintKit_Operation_CombineStage); }
        set { __pbn__stage = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
    }
    public bool ShouldSerializecombine_add() => __pbn__stage.Is(2);
    public void Resetcombine_add() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__stage, 2);

    [global::ProtoBuf.ProtoMember(3)]
    public CMsgPaintKit_Operation_CombineStage combine_lerp
    {
        get { return __pbn__stage.Is(3) ? ((CMsgPaintKit_Operation_CombineStage)__pbn__stage.Object) : default(CMsgPaintKit_Operation_CombineStage); }
        set { __pbn__stage = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
    }
    public bool ShouldSerializecombine_lerp() => __pbn__stage.Is(3);
    public void Resetcombine_lerp() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__stage, 3);

    [global::ProtoBuf.ProtoMember(4)]
    public CMsgPaintKit_Operation_CombineStage combine_multiply
    {
        get { return __pbn__stage.Is(4) ? ((CMsgPaintKit_Operation_CombineStage)__pbn__stage.Object) : default(CMsgPaintKit_Operation_CombineStage); }
        set { __pbn__stage = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
    }
    public bool ShouldSerializecombine_multiply() => __pbn__stage.Is(4);
    public void Resetcombine_multiply() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__stage, 4);

    [global::ProtoBuf.ProtoMember(5)]
    public CMsgPaintKit_Operation_SelectStage select
    {
        get { return __pbn__stage.Is(5) ? ((CMsgPaintKit_Operation_SelectStage)__pbn__stage.Object) : default(CMsgPaintKit_Operation_SelectStage); }
        set { __pbn__stage = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
    }
    public bool ShouldSerializeselect() => __pbn__stage.Is(5);
    public void Resetselect() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__stage, 5);

    [global::ProtoBuf.ProtoMember(6)]
    public CMsgPaintKit_Operation_StickerStage apply_sticker
    {
        get { return __pbn__stage.Is(6) ? ((CMsgPaintKit_Operation_StickerStage)__pbn__stage.Object) : default(CMsgPaintKit_Operation_StickerStage); }
        set { __pbn__stage = new global::ProtoBuf.DiscriminatedUnionObject(6, value); }
    }
    public bool ShouldSerializeapply_sticker() => __pbn__stage.Is(6);
    public void Resetapply_sticker() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__stage, 6);

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgPaintKit_OperationNode : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public CMsgPaintKit_OperationStage stage
    {
        get { return __pbn__node.Is(1) ? ((CMsgPaintKit_OperationStage)__pbn__node.Object) : default(CMsgPaintKit_OperationStage); }
        set { __pbn__node = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
    }
    public bool ShouldSerializestage() => __pbn__node.Is(1);
    public void Resetstage() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__node, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__node;

    [global::ProtoBuf.ProtoMember(2)]
    public CMsgProtoDefID operation_template
    {
        get { return __pbn__node.Is(2) ? ((CMsgProtoDefID)__pbn__node.Object) : default(CMsgProtoDefID); }
        set { __pbn__node = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
    }
    public bool ShouldSerializeoperation_template() => __pbn__node.Is(2);
    public void Resetoperation_template() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__node, 2);

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgPaintKit_Operation : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public CMsgProtoDefHeader header { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public global::System.Collections.Generic.List<CMsgPaintKit_OperationNode> operation_node { get; set; } = new global::System.Collections.Generic.List<CMsgPaintKit_OperationNode>();

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgPaintKit_ItemDefinition : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public CMsgProtoDefHeader header { get; set; }

    [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
    public uint item_definition_index { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public CMsgProtoDefID variable_template { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public global::System.Collections.Generic.List<Definition> definition { get; set; } = new global::System.Collections.Generic.List<Definition>();

    [global::ProtoBuf.ProtoContract()]
    public partial class Definition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public CMsgProtoDefID operation_template { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<CMsgVarField> variable { get; set; } = new global::System.Collections.Generic.List<CMsgVarField>();

    }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgPaintKit_Definition : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public CMsgProtoDefHeader header { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string loc_desctoken
    {
        get { return __pbn__loc_desctoken ?? ""; }
        set { __pbn__loc_desctoken = value; }
    }
    public bool ShouldSerializeloc_desctoken() => __pbn__loc_desctoken != null;
    public void Resetloc_desctoken() => __pbn__loc_desctoken = null;
    private string __pbn__loc_desctoken;

    [global::ProtoBuf.ProtoMember(3)]
    public CMsgProtoDefID operation_template { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public bool has_team_textures
    {
        get { return __pbn__has_team_textures.GetValueOrDefault(); }
        set { __pbn__has_team_textures = value; }
    }
    public bool ShouldSerializehas_team_textures() => __pbn__has_team_textures != null;
    public void Resethas_team_textures() => __pbn__has_team_textures = null;
    private bool? __pbn__has_team_textures;

    [global::ProtoBuf.ProtoMember(5)]
    public global::System.Collections.Generic.List<Item> item { get; set; } = new global::System.Collections.Generic.List<Item>();

    [global::ProtoBuf.ProtoMember(6)]
    public Item paintkit_tool { get; set; }

    [global::ProtoBuf.ProtoMember(7)]
    public Item flamethrower { get; set; }

    [global::ProtoBuf.ProtoMember(8)]
    public Item grenadelauncher { get; set; }

    [global::ProtoBuf.ProtoMember(9)]
    public Item knife { get; set; }

    [global::ProtoBuf.ProtoMember(10)]
    public Item medigun { get; set; }

    [global::ProtoBuf.ProtoMember(11)]
    public Item minigun { get; set; }

    [global::ProtoBuf.ProtoMember(12)]
    public Item pistol { get; set; }

    [global::ProtoBuf.ProtoMember(13)]
    public Item revolver { get; set; }

    [global::ProtoBuf.ProtoMember(14)]
    public Item rocketlauncher { get; set; }

    [global::ProtoBuf.ProtoMember(15)]
    public Item scattergun { get; set; }

    [global::ProtoBuf.ProtoMember(16)]
    public Item shotgun { get; set; }

    [global::ProtoBuf.ProtoMember(17)]
    public Item smg { get; set; }

    [global::ProtoBuf.ProtoMember(18)]
    public Item sniperrifle { get; set; }

    [global::ProtoBuf.ProtoMember(19)]
    public Item stickybomb_launcher { get; set; }

    [global::ProtoBuf.ProtoMember(20)]
    public Item ubersaw { get; set; }

    [global::ProtoBuf.ProtoMember(21)]
    public Item wrench { get; set; }

    [global::ProtoBuf.ProtoMember(22)]
    public Item amputator { get; set; }

    [global::ProtoBuf.ProtoMember(23)]
    public Item atom_launcher { get; set; }

    [global::ProtoBuf.ProtoMember(24)]
    public Item back_scratcher { get; set; }

    [global::ProtoBuf.ProtoMember(25)]
    public Item battleaxe { get; set; }

    [global::ProtoBuf.ProtoMember(26)]
    public Item bazaar_sniper { get; set; }

    [global::ProtoBuf.ProtoMember(27)]
    public Item blackbox { get; set; }

    [global::ProtoBuf.ProtoMember(28)]
    public Item claidheamohmor { get; set; }

    [global::ProtoBuf.ProtoMember(29)]
    public Item crusaders_crossbow { get; set; }

    [global::ProtoBuf.ProtoMember(30)]
    public Item degreaser { get; set; }

    [global::ProtoBuf.ProtoMember(31)]
    public Item demo_cannon { get; set; }

    [global::ProtoBuf.ProtoMember(32)]
    public Item demo_sultan_sword { get; set; }

    [global::ProtoBuf.ProtoMember(33)]
    public Item detonator { get; set; }

    [global::ProtoBuf.ProtoMember(34)]
    public Item gatling_gun { get; set; }

    [global::ProtoBuf.ProtoMember(35)]
    public Item holymackerel { get; set; }

    [global::ProtoBuf.ProtoMember(36)]
    public Item jag { get; set; }

    [global::ProtoBuf.ProtoMember(37)]
    public Item lochnload { get; set; }

    [global::ProtoBuf.ProtoMember(38)]
    public Item powerjack { get; set; }

    [global::ProtoBuf.ProtoMember(39)]
    public Item quadball { get; set; }

    [global::ProtoBuf.ProtoMember(40)]
    public Item reserve_shooter { get; set; }

    [global::ProtoBuf.ProtoMember(41)]
    public Item riding_crop { get; set; }

    [global::ProtoBuf.ProtoMember(42)]
    public Item russian_riot { get; set; }

    [global::ProtoBuf.ProtoMember(43)]
    public Item scimitar { get; set; }

    [global::ProtoBuf.ProtoMember(44)]
    public Item scorch_shot { get; set; }

    [global::ProtoBuf.ProtoMember(45)]
    public Item shortstop { get; set; }

    [global::ProtoBuf.ProtoMember(46)]
    public Item soda_popper { get; set; }

    [global::ProtoBuf.ProtoMember(47)]
    public Item tele_shotgun { get; set; }

    [global::ProtoBuf.ProtoMember(48)]
    public Item tomislav { get; set; }

    [global::ProtoBuf.ProtoMember(49)]
    public Item trenchgun { get; set; }

    [global::ProtoBuf.ProtoMember(50)]
    public Item winger_pistol { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public partial class Item : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public CMsgProtoDefID item_definition_template { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ItemData data { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class ItemData : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(2)]
            [global::System.ComponentModel.DefaultValue(true)]
            public bool can_apply_paintkit
            {
                get { return __pbn__can_apply_paintkit ?? true; }
                set { __pbn__can_apply_paintkit = value; }
            }
            public bool ShouldSerializecan_apply_paintkit() => __pbn__can_apply_paintkit != null;
            public void Resetcan_apply_paintkit() => __pbn__can_apply_paintkit = null;
            private bool? __pbn__can_apply_paintkit;

            [global::ProtoBuf.ProtoMember(3)]
            [global::System.ComponentModel.DefaultValue("")]
            public string material_override
            {
                get { return __pbn__material_override ?? ""; }
                set { __pbn__material_override = value; }
            }
            public bool ShouldSerializematerial_override() => __pbn__material_override != null;
            public void Resetmaterial_override() => __pbn__material_override = null;
            private string __pbn__material_override;

            [global::ProtoBuf.ProtoMember(4)]
            public global::System.Collections.Generic.List<CMsgVarField> variable { get; set; } = new global::System.Collections.Generic.List<CMsgVarField>();

        }

    }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgQuestTheme : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public CMsgProtoDefHeader header { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string notification_res
    {
        get { return __pbn__notification_res ?? ""; }
        set { __pbn__notification_res = value; }
    }
    public bool ShouldSerializenotification_res() => __pbn__notification_res != null;
    public void Resetnotification_res() => __pbn__notification_res = null;
    private string __pbn__notification_res;

    [global::ProtoBuf.ProtoMember(3)]
    [global::System.ComponentModel.DefaultValue("")]
    public string quest_item_res
    {
        get { return __pbn__quest_item_res ?? ""; }
        set { __pbn__quest_item_res = value; }
    }
    public bool ShouldSerializequest_item_res() => __pbn__quest_item_res != null;
    public void Resetquest_item_res() => __pbn__quest_item_res = null;
    private string __pbn__quest_item_res;

    [global::ProtoBuf.ProtoMember(4)]
    [global::System.ComponentModel.DefaultValue("")]
    public string in_game_tracker_res
    {
        get { return __pbn__in_game_tracker_res ?? ""; }
        set { __pbn__in_game_tracker_res = value; }
    }
    public bool ShouldSerializein_game_tracker_res() => __pbn__in_game_tracker_res != null;
    public void Resetin_game_tracker_res() => __pbn__in_game_tracker_res = null;
    private string __pbn__in_game_tracker_res;

    [global::ProtoBuf.ProtoMember(5)]
    public global::System.Collections.Generic.List<WeightedStringSet> give_sounds { get; set; } = new global::System.Collections.Generic.List<WeightedStringSet>();

    [global::ProtoBuf.ProtoMember(6)]
    public global::System.Collections.Generic.List<WeightedStringSet> complete_sounds { get; set; } = new global::System.Collections.Generic.List<WeightedStringSet>();

    [global::ProtoBuf.ProtoMember(7)]
    public global::System.Collections.Generic.List<WeightedStringSet> fully_complete_sounds { get; set; } = new global::System.Collections.Generic.List<WeightedStringSet>();

    [global::ProtoBuf.ProtoMember(8)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reward_sound
    {
        get { return __pbn__reward_sound ?? ""; }
        set { __pbn__reward_sound = value; }
    }
    public bool ShouldSerializereward_sound() => __pbn__reward_sound != null;
    public void Resetreward_sound() => __pbn__reward_sound = null;
    private string __pbn__reward_sound;

    [global::ProtoBuf.ProtoMember(9)]
    [global::System.ComponentModel.DefaultValue("")]
    public string discard_sound
    {
        get { return __pbn__discard_sound ?? ""; }
        set { __pbn__discard_sound = value; }
    }
    public bool ShouldSerializediscard_sound() => __pbn__discard_sound != null;
    public void Resetdiscard_sound() => __pbn__discard_sound = null;
    private string __pbn__discard_sound;

    [global::ProtoBuf.ProtoMember(10)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reveal_sound
    {
        get { return __pbn__reveal_sound ?? ""; }
        set { __pbn__reveal_sound = value; }
    }
    public bool ShouldSerializereveal_sound() => __pbn__reveal_sound != null;
    public void Resetreveal_sound() => __pbn__reveal_sound = null;
    private string __pbn__reveal_sound;

    [global::ProtoBuf.ProtoContract()]
    public partial class WeightedString : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string @string
        {
            get { return __pbn__string ?? ""; }
            set { __pbn__string = value; }
        }
        public bool ShouldSerializestring() => __pbn__string != null;
        public void Resetstring() => __pbn__string = null;
        private string __pbn__string;

        [global::ProtoBuf.ProtoMember(2)]
        public uint weight
        {
            get { return __pbn__weight.GetValueOrDefault(); }
            set { __pbn__weight = value; }
        }
        public bool ShouldSerializeweight() => __pbn__weight != null;
        public void Resetweight() => __pbn__weight = null;
        private uint? __pbn__weight;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WeightedStringSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<CMsgQuestTheme.WeightedString> weighted_strings { get; set; } = new global::System.Collections.Generic.List<CMsgQuestTheme.WeightedString>();

    }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgQuestMapNodeCondition_NodeState : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue(0)]
    public uint bonus_objectives_required
    {
        get { return __pbn__bonus_objectives_required ?? 0; }
        set { __pbn__bonus_objectives_required = value; }
    }
    public bool ShouldSerializebonus_objectives_required() => __pbn__bonus_objectives_required != null;
    public void Resetbonus_objectives_required() => __pbn__bonus_objectives_required = null;
    private uint? __pbn__bonus_objectives_required;

    [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
    public CMsgProtoDefID target_node_defid { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgQuestMapNodeCondition_Logic : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public LogicalOperation operation { get; set; } = LogicalOperation.AND;

    [global::ProtoBuf.ProtoMember(2)]
    public global::System.Collections.Generic.List<CMsgQuestMapNodeCondition> sub_conditions { get; set; } = new global::System.Collections.Generic.List<CMsgQuestMapNodeCondition>();

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgQuestMapNodeCondition : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public CMsgQuestMapNodeCondition_NodeState node_state
    {
        get { return __pbn__operation.Is(1) ? ((CMsgQuestMapNodeCondition_NodeState)__pbn__operation.Object) : default(CMsgQuestMapNodeCondition_NodeState); }
        set { __pbn__operation = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
    }
    public bool ShouldSerializenode_state() => __pbn__operation.Is(1);
    public void Resetnode_state() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__operation, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__operation;

    [global::ProtoBuf.ProtoMember(2)]
    public CMsgQuestMapNodeCondition_Logic logical
    {
        get { return __pbn__operation.Is(2) ? ((CMsgQuestMapNodeCondition_Logic)__pbn__operation.Object) : default(CMsgQuestMapNodeCondition_Logic); }
        set { __pbn__operation = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
    }
    public bool ShouldSerializelogical() => __pbn__operation.Is(2);
    public void Resetlogical() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__operation, 2);

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgHeaderOnly : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public CMsgProtoDefHeader header { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public enum LogicalOperation
{
    AND = 0,
    OR = 1,
    NOT = 2,
}

[global::ProtoBuf.ProtoContract()]
public enum EValueDefinitionSource
{
    REFERENCE_DEFINES = 0,
    PARENT_DEFINES = 1,
    THIS_DEFINES = 2,
    VARIABLE_DEFINES = 3,
    NOT_DEFINED = 4,
}

[global::ProtoBuf.ProtoContract()]
public enum ProtoDefTypes
{
    DEF_TYPE_QUEST_MAP_NODE = 0,
    DEF_TYPE_QUEST_THEME = 2,
    DEF_TYPE_QUEST_MAP_REGION = 3,
    DEF_TYPE_QUEST = 4,
    DEF_TYPE_QUEST_OBJECTIVE = 5,
    DEF_TYPE_PAINTKIT_VARIABLES = 6,
    DEF_TYPE_PAINTKIT_OPERATION = 7,
    DEF_TYPE_PAINTKIT_ITEM_DEFINITION = 8,
    DEF_TYPE_PAINTKIT_DEFINITION = 9,
    DEF_TYPE_HEADER_ONLY = 10,
    DEF_TYPE_QUEST_MAP_STORE_ITEM = 11,
    DEF_TYPE_QUEST_MAP_STAR_TYPE = 12,
}

[global::ProtoBuf.ProtoContract()]
public enum EQuestPoints
{
    QUEST_POINTS_NOVICE = 0,
    QUEST_POINTS_ADVANCED = 1,
    QUEST_POINTS_EXPERT = 2,
}

[global::ProtoBuf.ProtoContract()]
public enum EVarFieldType
{
    VAR_TYPE_INVALID = 1,
    VAR_TYPE_FLOAT = 2,
    VAR_TYPE_DOUBLE = 3,
    VAR_TYPE_UINT32 = 4,
    VAR_TYPE_UINT64 = 5,
    VAR_TYPE_SINT32 = 6,
    VAR_TYPE_SINT64 = 7,
    VAR_TYPE_BOOL = 8,
    VAR_TYPE_STRING = 9,
}

[global::ProtoBuf.ProtoContract()]
public enum ENodeCashReward
{
    CASH_REWARD_NONE = 1,
    CASH_REWARD_SMALL = 2,
    CASH_REWARD_MEDIUM = 3,
    CASH_REWARD_LARGE = 4,
}

public static partial class Extensions
{
    public static bool Getstart_expanded(this global::Google.Protobuf.Reflection.MessageOptions obj)
        => obj == null ? default(bool) : global::ProtoBuf.Extensible.GetValue<bool>(obj, 80000);

    public static void Setstart_expanded(this global::Google.Protobuf.Reflection.MessageOptions obj, bool value)
        => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 80000, value);

    public static ProtoDefTypes Getvalid_type(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(ProtoDefTypes) : global::ProtoBuf.Extensible.GetValue<ProtoDefTypes>(obj, 70000);

    public static void Setvalid_type(this global::Google.Protobuf.Reflection.FieldOptions obj, ProtoDefTypes value)
        => global::ProtoBuf.Extensible.AppendValue<ProtoDefTypes>(obj, 70000, value);

    public static bool Geteditable(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(bool) : global::ProtoBuf.Extensible.GetValue<bool>(obj, 70001);

    public static void Seteditable(this global::Google.Protobuf.Reflection.FieldOptions obj, bool value)
        => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 70001, value);

    public static bool Getlocalized(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(bool) : global::ProtoBuf.Extensible.GetValue<bool>(obj, 70002);

    public static void Setlocalized(this global::Google.Protobuf.Reflection.FieldOptions obj, bool value)
        => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 70002, value);

    public static bool Getdo_not_inherit(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(bool) : global::ProtoBuf.Extensible.GetValue<bool>(obj, 70003);

    public static void Setdo_not_inherit(this global::Google.Protobuf.Reflection.FieldOptions obj, bool value)
        => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 70003, value);

    public static string Getdisplay_name(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(string) : global::ProtoBuf.Extensible.GetValue<string>(obj, 70004);

    public static void Setdisplay_name(this global::Google.Protobuf.Reflection.FieldOptions obj, string value)
        => global::ProtoBuf.Extensible.AppendValue<string>(obj, 70004, value);

    public static string Getcomment(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(string) : global::ProtoBuf.Extensible.GetValue<string>(obj, 70005);

    public static void Setcomment(this global::Google.Protobuf.Reflection.FieldOptions obj, string value)
        => global::ProtoBuf.Extensible.AppendValue<string>(obj, 70005, value);

    public static uint Getmax_count(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(uint) : global::ProtoBuf.Extensible.GetValue<uint>(obj, 70007);

    public static void Setmax_count(this global::Google.Protobuf.Reflection.FieldOptions obj, uint value)
        => global::ProtoBuf.Extensible.AppendValue<uint>(obj, 70007, value);

    public static bool Getallow_add(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(bool) : global::ProtoBuf.Extensible.GetValue<bool>(obj, 70008);

    public static void Setallow_add(this global::Google.Protobuf.Reflection.FieldOptions obj, bool value)
        => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 70008, value);

    public static bool Getallow_delete(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(bool) : global::ProtoBuf.Extensible.GetValue<bool>(obj, 70009);

    public static void Setallow_delete(this global::Google.Protobuf.Reflection.FieldOptions obj, bool value)
        => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 70009, value);

    public static string Getpanel_class_override(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(string) : global::ProtoBuf.Extensible.GetValue<string>(obj, 70010);

    public static void Setpanel_class_override(this global::Google.Protobuf.Reflection.FieldOptions obj, string value)
        => global::ProtoBuf.Extensible.AppendValue<string>(obj, 70010, value);

    public static string Getmessage_inherhitance_key_field_name(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(string) : global::ProtoBuf.Extensible.GetValue<string>(obj, 70011);

    public static void Setmessage_inherhitance_key_field_name(this global::Google.Protobuf.Reflection.FieldOptions obj, string value)
        => global::ProtoBuf.Extensible.AppendValue<string>(obj, 70011, value);

    public static bool Getinherit_reference_variables(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(bool) : global::ProtoBuf.Extensible.GetValue<bool>(obj, 70012);

    public static void Setinherit_reference_variables(this global::Google.Protobuf.Reflection.FieldOptions obj, bool value)
        => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 70012, value);

    public static bool Getself_inherit_only(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(bool) : global::ProtoBuf.Extensible.GetValue<bool>(obj, 70013);

    public static void Setself_inherit_only(this global::Google.Protobuf.Reflection.FieldOptions obj, bool value)
        => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 70013, value);

    public static EVarFieldType Getvar_field_type(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(EVarFieldType) : global::ProtoBuf.Extensible.GetValue<EVarFieldType>(obj, 70014);

    public static void Setvar_field_type(this global::Google.Protobuf.Reflection.FieldOptions obj, EVarFieldType value)
        => global::ProtoBuf.Extensible.AppendValue<EVarFieldType>(obj, 70014, value);

    public static bool Getmerging_key_field(this global::Google.Protobuf.Reflection.FieldOptions obj)
        => obj == null ? default(bool) : global::ProtoBuf.Extensible.GetValue<bool>(obj, 70015);

    public static void Setmerging_key_field(this global::Google.Protobuf.Reflection.FieldOptions obj, bool value)
        => global::ProtoBuf.Extensible.AppendValue<bool>(obj, 70015, value);

}
#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion